import { Question } from './quizData';

export interface SasTrackInfo {
  id: 'all' | 'ml' | 'stats' | 'text';
  name: string;
  tagline: string;
  categoryIcon: string;
  folderName: string;
  topics: string[];
}

export const SAS_TRACKS: Record<string, SasTrackInfo> = {
  all: {
    id: 'all',
    name: 'SAS Global Certification Prep (Combined)',
    tagline: 'Comprehensive Exam covering Machine Learning, Applied Statistics & Text Analytics',
    categoryIcon: 'Sparkles',
    folderName: 'SAS_Learn Data',
    topics: [
      'SAS Viya Model Studio Pipeline Architecture',
      'Data Preprocessing, Transformations & Missing Value Imputation',
      'Decision Trees, Random Forests & Gradient Boosting',
      'Multilayer Perceptron Neural Networks & SVM',
      'Model Assessment (ROC, Lift Charts, KS Statistic, Misclassification)',
      'Ordinary Least Squares Assumptions & Collinearity (VIF, Cook\'s D)',
      'Logistic Regression & Logit Link Function',
      'Text Analytics Pipelines, Tokenization & Stop Lists',
      'LITI Concept & Category Rules Syntax',
      'Model Studio Auto-Tuning & Champion Model Selection',
    ],
  },
  ml: {
    id: 'ml',
    name: 'Machine Learning Using SAS Viya',
    tagline: 'Course CPML52: Decision Trees, Forests, Neural Networks & Model Studio',
    categoryIcon: 'Cpu',
    folderName: 'Machine Learning using sas viya (Parts)',
    topics: [
      'Model Studio Pipelines & Project Setup',
      'Data Preprocessing, Transformations & Imputation',
      'Decision Trees & Split Criterion (Chi-Square, Gini, Entropy)',
      'Forest & Gradient Boosting Ensemble Models',
      'Neural Networks (Multi-Layer Perceptrons, Hidden Units & Activation Functions)',
      'Support Vector Machines (Hyperplanes & Radial Basis Functions)',
      'Model Assessment (ROC Curves, Lift Charts, Cumulative Lift, KS Statistic)',
      'Hyperparameter Auto-Tuning in SAS Viya',
    ],
  },
  stats: {
    id: 'stats',
    name: 'Essential Statistics for Machine Learning',
    tagline: 'Course EVST152: Probability, Hypothesis Testing, Regression & Diagnostics',
    categoryIcon: 'Atom',
    folderName: 'Statistics need for ML (Parts)',
    topics: [
      'Descriptive Statistics, Variance, Skewness, and Kurtosis',
      'Normal Distribution, Central Limit Theorem & Confidence Intervals',
      'Hypothesis Testing, p-values, Type I & Type II Errors',
      'ANOVA (F-Tests, Within/Between Variance, Post-Hoc Tests)',
      'Linear Regression Assumptions (Normality, Homoscedasticity, Independence)',
      'Multicollinearity Diagnostics (Variance Inflation Factor VIF, Tolerance)',
      'Outlier & Influence Diagnostics (Cook\'s D, Studentized Residuals)',
      'Logistic Regression for Binary Classification & Logit Link Function',
    ],
  },
  text: {
    id: 'text',
    name: 'Visual Text Analytics Using SAS Viya',
    tagline: 'Course SVTA52: NLP, Parsing, Sentiment, Topics & LITI Rule Writing',
    categoryIcon: 'FileText',
    folderName: 'Text Analytics Using Sas Viya (Parts)',
    topics: [
      'Visual Text Analytics Architecture & Project Pipelines',
      'Text Parsing Node (Tokenization, Part-of-Speech Tagging, Stemming)',
      'Stop Lists and Start Lists Management',
      'Concept Rules and Taxonomy Creation (LITI Syntax: CLASSIFIER, CONCEPT_RULE)',
      'Sentiment Analysis Node (Document-level & Feature-level Sentiment)',
      'Topic Generation Node (Latent Dirichlet Allocation & Term Weights)',
      'Category Rules and Document Classification',
      'Scoring & Deploying Text Models in Production',
    ],
  },
};

// 20 High-Quality Certification Questions with Rich Learning Nodes & Jargon Glossaries
export const SAS_CERTIFICATION_20_BANK: Question[] = [
  // --- Machine Learning (1-7) ---
  {
    id: 101,
    category: 'SAS Machine Learning',
    categoryIcon: 'Cpu',
    difficulty: 'Medium',
    question: 'In SAS Viya Model Studio, which node allows you to simultaneously train and automatically tune hyperparameters for Decision Trees, Forest, and Gradient Boosting?',
    options: ['Supervised Learning Node', 'AutoTune option in supervised model nodes', 'Pipeline Comparison Node', 'Data Exploration Node'],
    correctIndex: 1,
    explanation: 'In SAS Viya, model nodes support AutoTune, an intelligent hyperparameter optimization framework that uses local and global search algorithms (e.g. Genetic Algorithm, Latin Hypercube) to find optimal hyperparameters.',
    funFact: 'SAS Viya AutoTune runs parallelized evaluations on CAS (Cloud Analytic Services) workers for massive speedup.',
    learningNode: {
      conceptSummary: 'AutoTune is SAS Viya\'s automated hyperparameter tuner. Instead of guessing how many trees to build or how deep they should go, AutoTune runs intelligent search algorithms across distributed cluster workers to find the optimal combination.',
      terminologies: [
        { term: 'Hyperparameter', definition: 'A configuration setting external to the model (like tree depth or learning rate) that is set before training begins.' },
        { term: 'CAS (Cloud Analytic Services)', definition: 'The high-performance, in-memory distributed analytics engine powering all calculations in SAS Viya.' },
        { term: 'Genetic Algorithm', definition: 'An optimization heuristic inspired by natural evolution that combines and mutates parameter sets to reach optimal model accuracy.' },
      ],
      certificationTakeaway: 'For the SAS Global Certification exam, remember that AutoTune is configured inside the individual Supervised Learning model nodes (under Autotuning options), NOT in the Pipeline Comparison node.',
    },
  },
  {
    id: 102,
    category: 'SAS Machine Learning',
    categoryIcon: 'Cpu',
    difficulty: 'Medium',
    question: 'Which metric in the SAS Viya Model Assessment node is best suited to evaluate model performance when dealing with heavily imbalanced binary target data (e.g., fraud rate < 1%)?',
    options: ['Misclassification Rate', 'Top Decile Lift and Cumulative Lift', 'Mean Squared Error', 'Training R-Squared'],
    correctIndex: 1,
    explanation: 'In rare-event problems, misclassification rate is misleading because simply predicting the majority class yields >99% accuracy. Lift charts evaluate how many times better the model is at capturing rare responders compared to random selection in the top deciles.',
    funFact: 'A Lift of 4.0 in the top 10% decile means your model captures 4 times more true responders than random outreach.',
    learningNode: {
      conceptSummary: 'When detecting rare events (like 5 fraud cases out of 1,000 transactions), standard accuracy is useless. Lift charts measure how concentrated your true positives are at the very top of your ranked score list.',
      terminologies: [
        { term: 'Top Decile Lift', definition: 'The ratio of responders in the top 10% ranked predictions compared to the baseline population response rate.' },
        { term: 'Cumulative Lift', definition: 'The total lift achieved when targeting through a given percentile (e.g., top 20% or 30%).' },
        { term: 'Imbalanced Target', definition: 'A dataset where one class (non-fraud) heavily outnumbers the other class (fraud).' },
      ],
      certificationTakeaway: 'SAS Certification questions frequently test this exact distinction: whenever a question mentions "rare event" or "imbalanced target", choose Cumulative Lift or Top Decile Lift over Misclassification Rate.',
    },
  },
  {
    id: 103,
    category: 'SAS Machine Learning',
    categoryIcon: 'Cpu',
    difficulty: 'Hard',
    question: 'What is the fundamental architectural difference between the Forest node and the Gradient Boosting node in SAS Viya?',
    options: [
      'Forest builds deep independent trees in parallel using bagging; Gradient Boosting builds shallow trees sequentially to correct prior errors',
      'Forest only supports continuous targets while Gradient Boosting only supports nominal targets',
      'Gradient Boosting cannot handle missing values whereas Forest can',
      'Forest uses backpropagation whereas Gradient Boosting uses gradient ascent',
    ],
    correctIndex: 0,
    explanation: 'The Forest node creates an ensemble of independent full-grown decision trees trained on bootstrap samples with random feature subsets. Gradient Boosting builds shallow trees sequentially, where each consecutive tree predicts the pseudo-residuals of the previous trees.',
    funFact: 'SAS Viya Gradient Boosting leverages Cloud Analytic Services (CAS) to distribute tree partition computations across all cluster nodes.',
    learningNode: {
      conceptSummary: 'Think of Forest as a democracy where hundreds of independent decision trees vote. Think of Gradient Boosting as a master student learning sequentially, where each new tree specifically focuses on fixing the mistakes made by the previous trees.',
      terminologies: [
        { term: 'Bagging (Bootstrap Aggregating)', definition: 'Training multiple independent models on random subsets of rows and features, then averaging their predictions.' },
        { term: 'Boosting', definition: 'An iterative ensemble method where subsequent trees fit to the pseudo-residuals (errors) of prior iterations.' },
        { term: 'Pseudo-Residuals', definition: 'The gradient of the loss function with respect to model predictions, representing the direction and magnitude of error.' },
      ],
      certificationTakeaway: 'Exam Watch: Forest relies on Bagging (variance reduction, parallel trees), while Gradient Boosting relies on Sequential Residual Correction (bias reduction, shallow trees).',
    },
  },
  {
    id: 104,
    category: 'SAS Machine Learning',
    categoryIcon: 'Cpu',
    difficulty: 'Easy',
    question: 'Before passing continuous input variables into a Neural Network node in SAS Viya, what preprocessing step is strictly recommended to avoid convergence issues?',
    options: ['One-hot text parsing', 'Standardization / Range scaling', 'Polynomial expansion to 10th degree', 'Converting all values to negative numbers'],
    correctIndex: 1,
    explanation: 'Neural network optimization algorithms (like L-BFGS and SGD) require standardized or range-scaled inputs so that weight gradients are balanced across variables with differing scales.',
    funFact: 'SAS Viya Neural Network node automatically applies standardization (Midrange or Standard Deviation) by default.',
    learningNode: {
      conceptSummary: 'If Variable A is Income ($100,000) and Variable B is Age (25), unscaled gradients will be dominated entirely by Income. Standardization puts both on an equal scale (e.g. mean 0, variance 1).',
      terminologies: [
        { term: 'Standardization', definition: 'Rescaling features so they have a mean of 0 and a standard deviation of 1 (Z-score transformation).' },
        { term: 'L-BFGS', definition: 'Limited-memory Broyden-Fletcher-Goldfarb-Shanno algorithm, a quasi-Newton optimization method used for neural net weights in SAS.' },
        { term: 'Activation Function', definition: 'A mathematical function (e.g., Sigmoid, Tanh, ReLU) applied to hidden unit outputs to introduce non-linearity.' },
      ],
      certificationTakeaway: 'The SAS exam will ask why input standardization matters: the correct answer is always "to ensure optimization gradients are scale-independent and weights converge efficiently".',
    },
  },
  {
    id: 105,
    category: 'SAS Machine Learning',
    categoryIcon: 'Cpu',
    difficulty: 'Medium',
    question: 'In Model Studio Pipeline Comparison, which criterion is utilized to crown the "Champion Model" by default for a binary classification pipeline?',
    options: [
      'The model with the highest training accuracy',
      'The model with the best validation partition metric (such as KS Statistic or Misclassification Rate)',
      'The model that required the fewest iterations to train',
      'The model with the most inputs',
    ],
    correctIndex: 1,
    explanation: 'SAS Model Studio compares competing pipelines using validation partition fit statistics (e.g. KS, Misclassification, or Average Squared Error) to guard against overfitting and select the true champion.',
    funFact: 'You can easily override the champion selection criterion in Pipeline Settings to match business KPIs like Lift or AUC.',
    learningNode: {
      conceptSummary: 'A champion model must excel on unseen validation data, never on training data alone. A model that scores 100% on training data might just have memorized noise (overfitting).',
      terminologies: [
        { term: 'Champion Model', definition: 'The winning pipeline model chosen for scoring and production deployment in SAS Model Studio.' },
        { term: 'Validation Partition', definition: 'A subset of data held out during training specifically used to tune parameters and compare competing models.' },
        { term: 'Overfitting', definition: 'When a model learns the training noise so tightly that it fails to generalize to new, real-world data.' },
      ],
      certificationTakeaway: 'Always remember: Champion selection is ALWAYS decided on the VALIDATION partition, never the training partition.',
    },
  },
  {
    id: 106,
    category: 'SAS Machine Learning',
    categoryIcon: 'Cpu',
    difficulty: 'Hard',
    question: 'In Support Vector Machines (SVM) in SAS Viya, how is non-linear class separation achieved when data cannot be separated by a straight hyperplane?',
    options: [
      'By applying a Kernel Function (such as Radial Basis Function RBF) to map data into a higher-dimensional space',
      'By randomly dropping half of the features',
      'By converting the continuous inputs into text documents',
      'By running linear regression iteratively',
    ],
    correctIndex: 0,
    explanation: 'The "Kernel Trick" in SVM uses mathematical kernel functions (like Gaussian RBF or Polynomial) to implicitly map input features into a higher-dimensional feature space where linear separation becomes possible.',
    funFact: 'In SAS Viya, the SVM node runs in CAS and supports both linear and radial basis function (RBF) kernels.',
    learningNode: {
      conceptSummary: 'Imagine blue dots in a circle surrounded by red dots on a 2D sheet of paper. You cannot draw a straight line to separate them. But if you push the blue dots up into the 3rd dimension (height), a flat sheet (hyperplane) can slice right underneath them!',
      terminologies: [
        { term: 'Kernel Function', definition: 'A function that computes the inner product between images of pairs of points in a transformed feature space without explicitly calculating coordinates.' },
        { term: 'Hyperplane', definition: 'A decision boundary that separates data classes in an n-dimensional space.' },
        { term: 'Support Vectors', definition: 'The data points closest to the hyperplane that dictate its position and maximum margin.' },
      ],
      certificationTakeaway: 'Key exam point: Kernel functions transform input space into higher dimensions to achieve linear separability without the computational penalty of explicit coordinate expansion.',
    },
  },
  {
    id: 107,
    category: 'SAS Machine Learning',
    categoryIcon: 'Cpu',
    difficulty: 'Medium',
    question: 'Which node in SAS Viya Model Studio is explicitly used to reduce dimensional redundancy by finding linear combinations of variables that explain maximal variance?',
    options: ['Principal Component Analysis (PCA) Node', 'Text Parsing Node', 'Replacement Node', 'Ensemble Node'],
    correctIndex: 0,
    explanation: 'The Principal Component Analysis (PCA) node performs unsupervised dimensionality reduction, transforming correlated variables into a smaller set of orthogonal components that retain most of the variance.',
    funFact: 'PCA in SAS Viya uses CAS eigen-decomposition to handle millions of rows in seconds.',
    learningNode: {
      conceptSummary: 'PCA condenses 50 correlated variables into 5 uncorrelated master components, preserving 90% of the information while drastically speeding up model training.',
      terminologies: [
        { term: 'Eigenvalue', definition: 'Represents the amount of variance explained by a specific principal component.' },
        { term: 'Orthogonal', definition: 'Perpendicular or mathematically uncorrelated; principal components are strictly orthogonal to one another.' },
        { term: 'Dimensionality Reduction', definition: 'The process of reducing the number of input variables while preserving essential structural information.' },
      ],
      certificationTakeaway: 'In SAS Viya data preprocessing questions, identify PCA as the primary node for orthogonal feature extraction and variance preservation.',
    },
  },

  // --- Statistics for Machine Learning (8-14) ---
  {
    id: 201,
    category: 'Statistics for ML',
    categoryIcon: 'Atom',
    difficulty: 'Easy',
    question: 'In linear regression analysis, what does a Variance Inflation Factor (VIF) greater than 10 typically indicate?',
    options: ['Extreme skewness of the residual errors', 'Severe multicollinearity among predictor variables', 'Heteroscedasticity in the target variable', 'Non-linear relationship with response'],
    correctIndex: 1,
    explanation: 'VIF measures how much the variance of an estimated regression coefficient increases when predictors are correlated. A VIF exceeding 5 to 10 indicates problematic multicollinearity that destabilizes coefficient estimates.',
    funFact: 'VIF is directly computed as 1 / (1 - R_i²), where R_i² is the coefficient of determination from regressing x_i on all other predictors.',
    learningNode: {
      conceptSummary: 'Multicollinearity means two or more predictor variables are saying the exact same thing (like Height in Inches and Height in Centimeters). When both are included, the math gets confused about who deserves credit for the prediction.',
      terminologies: [
        { term: 'Variance Inflation Factor (VIF)', definition: 'An index that measures how much the variance of an estimated regression coefficient is inflated due to collinearity.' },
        { term: 'Tolerance', definition: 'The reciprocal of VIF (1 / VIF). A tolerance below 0.1 indicates severe collinearity.' },
        { term: 'Multicollinearity', definition: 'High correlation between two or more independent variables in a regression model.' },
      ],
      certificationTakeaway: 'Exam Benchmark: A VIF > 10 (or Tolerance < 0.10) is the universal threshold used on SAS exams to flag severe multicollinearity requiring variable removal or combination.',
    },
  },
  {
    id: 202,
    category: 'Statistics for ML',
    categoryIcon: 'Atom',
    difficulty: 'Medium',
    question: 'Which diagnostic metric is commonly used in regression modeling to detect observations that have both high leverage AND large residuals (influential outliers)?',
    options: ['Cook\'s Distance (Cook\'s D)', 'Pearson Correlation Coefficient', 'Durbin-Watson Statistic', 'Student\'s t critical value'],
    correctIndex: 0,
    explanation: 'Cook\'s Distance measures the aggregate change in regression estimates when a specific observation is excluded. Points with Cook\'s D > 4/n or > 1 are deemed highly influential.',
    funFact: 'SAS REG and GLMSELECT procedures output Cook\'s D and RStudent residual diagnostics with one simple statement.',
    learningNode: {
      conceptSummary: 'An outlier is just an unusual point. But an influential point is a point that tilts the entire regression line towards itself. Cook\'s Distance pinpoints these heavy-gravity points.',
      terminologies: [
        { term: 'Cook\'s Distance', definition: 'A summary metric that combines an observation\'s leverage and studentized residual to measure its influence on all fitted values.' },
        { term: 'Leverage', definition: 'How far an observation\'s predictor values deviate from the mean of the predictors (extreme X value).' },
        { term: 'Residual', definition: 'The vertical difference between the actual observed value Y and the model predicted value Y-hat.' },
      ],
      certificationTakeaway: 'Distinguish between Leverage (unusual X) vs. Outlier (unusual Y) vs. Cook\'s D (influential in both X and Y simultaneously).',
    },
  },
  {
    id: 203,
    category: 'Statistics for ML',
    categoryIcon: 'Atom',
    difficulty: 'Medium',
    question: 'When performing hypothesis testing in SAS, what is a Type II Error (Beta)?',
    options: [
      'Failing to reject the null hypothesis when it is actually false',
      'Rejecting the null hypothesis when it is actually true',
      'Calculating an incorrect p-value due to sample size',
      'Accepting a model with low R-squared',
    ],
    correctIndex: 0,
    explanation: 'A Type II error (false negative) occurs when the test fails to reject a false null hypothesis. The statistical power of a test equals 1 - Beta.',
    funFact: 'In medical diagnosis or fraud screening, Type II errors are often far more costly than Type I errors (false alarms).',
    learningNode: {
      conceptSummary: 'Type I Error: A false alarm (saying a fire is happening when there is none). Type II Error: A missed detection (failing to sound the alarm when there is a real fire).',
      terminologies: [
        { term: 'Null Hypothesis (H0)', definition: 'The default baseline assumption that there is no effect, no difference, or no relationship.' },
        { term: 'Type I Error (Alpha)', definition: 'Rejecting the true null hypothesis (false positive).' },
        { term: 'Type II Error (Beta)', definition: 'Failing to reject a false null hypothesis (false negative).' },
        { term: 'Statistical Power', definition: 'The probability of correctly rejecting a false null hypothesis, defined as 1 - Beta.' },
      ],
      certificationTakeaway: 'Remember the mnemonic: Type I = False Positive; Type II = False Negative. Power = 1 - Beta.',
    },
  },
  {
    id: 204,
    category: 'Statistics for ML',
    categoryIcon: 'Atom',
    difficulty: 'Hard',
    question: 'In Logistic Regression, the log-odds (logit) transformation of probability p is expressed mathematically as:',
    options: ['ln(p / (1 - p))', 'p / (1 + p)', 'exp(p) * ln(1 - p)', '1 / (1 + e^p)'],
    correctIndex: 0,
    explanation: 'The logit link function is the natural logarithm of the odds: logit(p) = ln(p / (1 - p)). It maps probability values from [0, 1] to (-∞, +∞).',
    funFact: 'Exponentiating the logistic regression parameter estimates gives the odds ratio for a one-unit change in the predictor.',
    learningNode: {
      conceptSummary: 'Probabilities are bounded between 0 and 1. Standard regression outputs numbers from -infinity to +infinity. The logit function transforms the bounded 0-1 probability into unbounded numbers so linear models can be fitted.',
      terminologies: [
        { term: 'Odds', definition: 'The ratio of the probability of success to the probability of failure: p / (1 - p).' },
        { term: 'Logit Link', definition: 'The natural log of odds: ln(p / (1 - p)).' },
        { term: 'Odds Ratio (OR)', definition: 'exp(Beta_i), representing the multiplicative change in odds for every 1-unit increase in predictor X_i.' },
      ],
      certificationTakeaway: 'Exam questions will ask: "If Beta_1 = 0.693 in a logistic regression, what is the effect on the odds?" Answer: exp(0.693) ≈ 2.0 (the odds double for each unit increase).',
    },
  },
  {
    id: 205,
    category: 'Statistics for ML',
    categoryIcon: 'Atom',
    difficulty: 'Easy',
    question: 'What assumption of Ordinary Least Squares (OLS) linear regression states that residual errors must have constant variance across all levels of the predictor?',
    options: ['Homoscedasticity', 'Normality', 'Multicollinearity', 'Independence'],
    correctIndex: 0,
    explanation: 'Homoscedasticity means the variance of the residuals remains uniform across all predicted values. Violations are termed heteroscedasticity.',
    funFact: 'A funnel shape in a Residual vs. Fitted plot is the classic visual signal of heteroscedasticity.',
    learningNode: {
      conceptSummary: 'Homoscedasticity means your prediction error spread stays identical whether you are predicting for low values or high values. If errors blow up into a wide fan or funnel shape as values increase, homoscedasticity is broken.',
      terminologies: [
        { term: 'Homoscedasticity', definition: 'Equal or constant variance of the error terms across all levels of the independent variables.' },
        { term: 'Heteroscedasticity', definition: 'Non-constant error variance, which makes standard error estimates invalid and p-values unreliable.' },
        { term: 'Residual Plot', definition: 'A scatter plot of residuals vs. predicted values used to visually verify regression assumptions.' },
      ],
      certificationTakeaway: 'Funnel or megaphone shapes in residual plots = Heteroscedasticity. Solution: Log transformation of the target variable or weighted least squares.',
    },
  },
  {
    id: 206,
    category: 'Statistics for ML',
    categoryIcon: 'Atom',
    difficulty: 'Medium',
    question: 'In One-Way Analysis of Variance (ANOVA), what does the F-statistic test?',
    options: [
      'The ratio of Between-Group Variance to Within-Group Variance',
      'The correlation between continuous inputs',
      'The difference between the median and the mode',
      'The total number of missing observations',
    ],
    correctIndex: 0,
    explanation: 'ANOVA evaluates whether group means differ significantly by comparing the variance between the treatment groups (Mean Square Between) to the random error variance within the groups (Mean Square Error): F = MSB / MSE.',
    funFact: 'If the group means are truly identical, the expected value of the F-statistic is approximately 1.0.',
    learningNode: {
      conceptSummary: 'ANOVA answers: "Are the differences between our groups bigger than the random background noise inside each group?" If the between-group noise is huge compared to inside noise, F is large and we reject equality of means.',
      terminologies: [
        { term: 'F-Statistic', definition: 'Ratio of Mean Square Between groups (treatment signal) to Mean Square Error (background noise).' },
        { term: 'Post-Hoc Test', definition: 'Pairwise tests (like Tukey\'s HSD) conducted after a significant ANOVA to identify exactly which specific pairs of groups differ.' },
        { term: 'Degrees of Freedom (DF)', definition: 'Number of independent values that can vary in the analysis, partitioned into model DF and error DF.' },
      ],
      certificationTakeaway: 'F = MS_Model / MS_Error. A large F-statistic and p-value < 0.05 indicates at least one group mean is significantly different.',
    },
  },
  {
    id: 207,
    category: 'Statistics for ML',
    categoryIcon: 'Atom',
    difficulty: 'Hard',
    question: 'In binary classification model assessment in SAS Viya, what does the KS (Kolmogorov-Smirnov) statistic represent?',
    options: [
      'The maximum vertical distance between the cumulative distribution curves of responders and non-responders',
      'The mean difference between training and validation accuracy',
      'The number of trees in a random forest',
      'The ratio of true positives to false positives',
    ],
    correctIndex: 0,
    explanation: 'The KS statistic measures the maximum separation between the cumulative distribution functions of events and non-events. A higher KS indicates stronger discrimination ability.',
    funFact: 'In credit risk modeling, a KS statistic above 40 is widely considered a benchmark for a high-performing scorecard.',
    learningNode: {
      conceptSummary: 'Imagine lining up all people who defaulted on a loan and all people who repaid. The KS statistic checks the point where your model creates the widest gap between good and bad payers.',
      terminologies: [
        { term: 'KS Statistic', definition: 'The maximum vertical gap between the cumulative distribution functions of events and non-events.' },
        { term: 'Cumulative Distribution Function (CDF)', definition: 'A function giving the probability that a random variable is less than or equal to a specified cutoff value.' },
        { term: 'Discrimination', definition: 'The ability of a diagnostic model to correctly separate cases with the target condition from cases without it.' },
      ],
      certificationTakeaway: 'KS is expressed between 0 and 100 (or 0.0 to 1.0). High KS = superior classification separation.',
    },
  },

  // --- Visual Text Analytics (15-20) ---
  {
    id: 301,
    category: 'SAS Text Analytics',
    categoryIcon: 'FileText',
    difficulty: 'Easy',
    question: 'In the SAS Visual Text Analytics Text Parsing node, what is the role of a "Stop List"?',
    options: [
      'To filter out common words (like "the", "and", "is") that carry little semantic information',
      'To halt pipeline execution when a malformed document is encountered',
      'To store only the keywords that must be extracted as concepts',
      'To limit document length to 500 characters',
    ],
    correctIndex: 0,
    explanation: 'A stop list contains noise words and conjunctions that are removed during parsing to reduce dimensionality and focus on meaningful content words.',
    funFact: 'SAS provides curated domain-specific stop lists across multiple languages out of the box in SAS Viya.',
    learningNode: {
      conceptSummary: 'Every text has filler words like "a", "an", "the", "with". Stop lists filter these out so the machine can focus on high-value terms like "battery", "overheating", or "refund".',
      terminologies: [
        { term: 'Stop List', definition: 'A controlled list of common words omitted from NLP analysis to save memory and eliminate noise.' },
        { term: 'Start List', definition: 'A controlled list that specifies ONLY the terms allowed to be parsed, discarding everything else.' },
        { term: 'Tokenization', definition: 'Breaking raw textual strings into individual words, terms, or punctuation marks.' },
      ],
      certificationTakeaway: 'Stop List = words to IGNORE. Start List = ONLY words to KEEP. This is a staple exam question.',
    },
  },
  {
    id: 302,
    category: 'SAS Text Analytics',
    categoryIcon: 'FileText',
    difficulty: 'Medium',
    question: 'In SAS Visual Text Analytics LITI (Language Interpretation and Text Interpretation) syntax, which operator is used to define a simple list of literal words or terms for a Concept rule?',
    options: ['CLASSIFIER:', 'PREDICATE_RULE:', 'TOPIC_FILTER:', 'REGEX_MATCH:'],
    correctIndex: 0,
    explanation: 'The CLASSIFIER: rule is used in LITI rule definition to extract strings that match any of the listed literal values or surface forms.',
    funFact: 'LITI rule syntax allows you to combine deterministic linguistic patterns with machine learning models for hybrid NLP.',
    learningNode: {
      conceptSummary: 'CLASSIFIER: is the simplest LITI rule. It tells SAS: "Whenever you see \'laptop\', \'notebook\', or \'MacBook\', tag it as a Computer concept."',
      terminologies: [
        { term: 'LITI (Language & Text Interpretation)', definition: 'SAS Viya\'s proprietary linguistic rule-writing language for concept and category creation.' },
        { term: 'CLASSIFIER:', definition: 'LITI operator for literal string and vocabulary matching.' },
        { term: 'Concept', definition: 'An entity or semantic pattern (e.g. Product, Medical Symptom, Currency) identified in unstructured text.' },
      ],
      certificationTakeaway: 'Rule Syntax Memorization: `CLASSIFIER:word1, word2, word3` extracts matching tokens verbatim.',
    },
  },
  {
    id: 303,
    category: 'SAS Text Analytics',
    categoryIcon: 'FileText',
    difficulty: 'Medium',
    question: 'Which node in a SAS Visual Text Analytics pipeline automatically groups documents into unlabelled clusters of co-occurring terms without requiring predefined rules?',
    options: ['Topics Node', 'Text Parsing Node', 'Concepts Node', 'Categories Node'],
    correctIndex: 0,
    explanation: 'The Topics Node applies singular value decomposition (SVD) and Latent Dirichlet Allocation (LDA) to automatically identify underlying themes across unstructured text documents.',
    funFact: 'In SAS Viya, topics can be converted directly into Category rules with a single click in the user interface.',
    learningNode: {
      conceptSummary: 'The Topics node is unsupervised machine learning for text. It reads 10,000 customer reviews and automatically realizes: "One group of reviews talks about airline food, another talks about lost baggage, and a third talks about seat legroom."',
      terminologies: [
        { term: 'Topics Node', definition: 'Unsupervised NLP node that extracts themes based on term co-occurrence matrices.' },
        { term: 'SVD (Singular Value Decomposition)', definition: 'Matrix factorization technique used in Latent Semantic Analysis (LSA) to uncover latent themes.' },
        { term: 'Term Weight', definition: 'The statistical importance of a term in defining a specific topic.' },
      ],
      certificationTakeaway: 'Concepts and Categories are rule/supervised-driven. Topics Node is UNSUPERVISED discovery.',
    },
  },
  {
    id: 304,
    category: 'SAS Text Analytics',
    categoryIcon: 'FileText',
    difficulty: 'Hard',
    question: 'In SAS Visual Text Analytics Concept rules, what is the exact function of the `_c{...}` operator in a CONCEPT_RULE?',
    options: [
      'It marks the exact portion of the matched string that is extracted as the target concept match',
      'It converts the extracted string to lowercase',
      'It counts the occurrences of the character in the document',
      'It designates the document as classified',
    ],
    correctIndex: 0,
    explanation: 'The `_c{}` argument identifies the specific matched token or span of tokens to be returned as the concept highlight, ignoring the surrounding context tokens used only for matching.',
    funFact: 'For example: `CONCEPT_RULE:(SENT, "cost", "_c{_NUMBER}")` captures the number only when "cost" appears in the same sentence.',
    learningNode: {
      conceptSummary: '`_c{}` is your highlighter pen. It tells SAS: "I needed to see the word \'Price:\' to know this was relevant, but only highlight and extract the dollar amount inside `_c{$50}`."',
      terminologies: [
        { term: '_c{} (Concept Capture)', definition: 'The capture operator in SAS LITI syntax defining the boundary of the entity to extract.' },
        { term: 'CONCEPT_RULE', definition: 'LITI rule type that uses contextual constraints (like SENT, ORD, CLAUSE) to match entities.' },
        { term: 'Context Token', definition: 'Words required to trigger the rule that are not part of the final concept extract.' },
      ],
      certificationTakeaway: 'Exam Question Classic: In `CONCEPT_RULE:(SENT, "patient", "_c{_medication}")`, what gets extracted? Answer: ONLY the medication name.',
    },
  },
  {
    id: 305,
    category: 'SAS Text Analytics',
    categoryIcon: 'FileText',
    difficulty: 'Medium',
    question: 'How does Sentiment Analysis in SAS Visual Text Analytics evaluate sentiment on a document with both praise and criticism?',
    options: [
      'It computes both document-level sentiment and granular feature-level (aspect-based) sentiment',
      'It only outputs binary positive or negative based on the first word',
      'It always defaults to neutral if any negative word is found',
      'It discards documents with mixed emotions',
    ],
    correctIndex: 0,
    explanation: 'SAS Visual Text Analytics performs aspect-based feature sentiment, allowing users to see that a hotel review has positive sentiment for "cleanliness" but negative sentiment for "price".',
    funFact: 'Aspect-based sentiment helps businesses pin-point specific product features that need operational improvement.',
    learningNode: {
      conceptSummary: 'If someone writes "The camera is amazing, but the battery is terrible", document-level sentiment might say "Neutral". Feature-level sentiment is smarter: Camera = +Positive, Battery = -Negative.',
      terminologies: [
        { term: 'Aspect-Based Sentiment', definition: 'Evaluating sentiment toward specific entities, products, or attributes rather than the document as a whole.' },
        { term: 'Document-Level Sentiment', definition: 'An aggregate overall polarity score for the entire text document.' },
        { term: 'Polarity', definition: 'The emotional direction of text: Positive, Negative, or Neutral.' },
      ],
      certificationTakeaway: 'Feature-Level Sentiment = Granular entity sentiment. Document-Level Sentiment = Overall summary.',
    },
  },
  {
    id: 306,
    category: 'SAS Text Analytics',
    categoryIcon: 'FileText',
    difficulty: 'Hard',
    question: 'In SAS Visual Text Analytics, what is the role of the Stemming process during Text Parsing?',
    options: [
      'Reducing inflected or derived words to their base or root stem form (e.g., "running", "runs" -> "run")',
      'Eliminating all numbers from text documents',
      'Converting foreign languages to English',
      'Generating synthetic text using language models',
    ],
    correctIndex: 0,
    explanation: 'Stemming maps morphologically related variants of a word to a common root form, reducing vocabulary dimensionality and grouping related usage.',
    funFact: 'SAS Viya combines dictionary-based lemmatization and algorithmic stemming for high precision across multiple languages.',
    learningNode: {
      conceptSummary: 'Stemming collapses "invest", "investing", "invested", and "invests" into a single root so that your analytics model recognizes they all share the exact same underlying meaning.',
      terminologies: [
        { term: 'Stemming', definition: 'Algorithmic truncation of suffixes and prefixes to reduce words to a common base form.' },
        { term: 'Lemmatization', definition: 'Morphological analysis using a vocabulary and grammatical rules to return the dictionary base form (lemma).' },
        { term: 'Term Frequency', definition: 'The count of occurrences of a parsed term within a document.' },
      ],
      certificationTakeaway: 'Stemming reduces feature dimensionality by consolidating related word variants into one root term.',
    },
  },
];
